// src/core/index.js
require('dotenv').config();
const FATAL_EXIT_ON_EXCEPTION = String(process.env.FATAL_EXIT_ON_EXCEPTION || '').toLowerCase() === 'true';
process.on('unhandledRejection', (reason) => { console.error('\u274c [Process] unhandledRejection:', reason); });
process.on('uncaughtException', (err) => { console.error('\u274c [Process] uncaughtException:', err); if (FATAL_EXIT_ON_EXCEPTION) { process.exit(1); } });
const { Client, Collection, Events, GatewayIntentBits } = require('discord.js');
const { clientReadyHandler } = require('./events/clientReady');
const { interactionCreateHandler } = require('./events/interactionCreate');
const { startProposalChecker } = require('../modules/proposal/services/proposalChecker');
const { startCourtChecker } = require('../modules/court/services/courtChecker');
const { startSelfModerationChecker } = require('../modules/selfModeration/services/moderationChecker');
const { startAttachmentCleanupScheduler } = require('../modules/selfModeration/services/archiveService');
const { startVoteChecker } = require('../modules/voting/services/voteChecker');
const { printTimeConfig } = require('./config/timeconfig');
const { startActivityTracker } = require('../modules/selfRole/services/activityTracker');
const { syncMissedActivity } = require('../modules/selfRole/services/autoSyncService');
const { startSelfRoleApplicationChecker } = require('../modules/selfRole/services/applicationChecker');
const { startSelfRoleLifecycleScheduler } = require('../modules/selfRole/services/lifecycleScheduler');
const { startSelfRoleConsistencyChecker } = require('../modules/selfRole/services/consistencyChecker');
const { startRoleSyncSystem, roleSyncGuildMemberAddHandler, roleSyncGuildMemberRemoveHandler, roleSyncGuildMemberUpdateHandler, roleSyncGuildRoleDeleteHandler } = require('../modules/roleSync');
const pingCommand = require('../shared/commands/ping');
const setCheckChannelCommand = require('../shared/commands/setCheckChannel');
const setupFormCommand = require('../modules/proposal/commands/setupForm');
const deleteEntryCommand = require('../modules/proposal/commands/deleteEntry');
const withdrawProposalCommand = require('../modules/proposal/commands/withdrawProposal');
const setFormPermissionsCommand = require('../modules/proposal/commands/setFormPermissions');
const setSupportPermissionsCommand = require('../modules/proposal/commands/setSupportPermissions');
const reviewProposalCommand = require('../modules/proposal/commands/reviewProposal');
const setProposalReviewersCommand = require('../modules/proposal/commands/setProposalReviewers');
const creatorReviewCommand = require('../modules/creatorReview/commands/creatorReview');
const setAllowCourtRoleCommand = require('../modules/court/commands/setAllowCourtRole');
const applyToCourtCommand = require('../modules/court/commands/applyToCourt');
const deleteShitMessageCommand = require('../modules/selfModeration/commands/deleteShitMessage');
const muteShitUserCommand = require('../modules/selfModeration/commands/muteShitUser');
const seriousMuteCommand = require('../modules/selfModeration/commands/seriousMute');
const selfModerationConfigCommand = require('../modules/selfModeration/commands/selfModerationConfig');
const checkMyCooldownCommand = require('../modules/selfModeration/commands/checkMyCooldown');
const getArchiveViewPermissionCommand = require('../modules/selfModeration/commands/getArchiveViewPermission');
const setupContestApplicationCommand = require('../modules/contest/commands/setupContestApplication');
const manageTrackCommand = require('../modules/contest/commands/manageTrack');
const setContestReviewersCommand = require('../modules/contest/commands/setContestReviewers');
const reviewContestApplicationCommand = require('../modules/contest/commands/reviewContestApplication');
const updateContestInfoCommand = require('../modules/contest/commands/updateContestInfo');
const updateContestTitleCommand = require('../modules/contest/commands/updateContestTitle');
const initContestTagsCommand = require('../modules/contest/commands/initContestTags');
const manageAllowedForumsCommand = require('../modules/contest/commands/manageAllowedForums');
const manageExternalServersCommand = require('../modules/contest/commands/manageExternalServers');
const cacheStats = require('../modules/contest/commands/cacheStats');
const regenerateContestMessagesCommand = require('../modules/contest/commands/regenerateContestMessages');
const bindParticipantRoleCommand = require('../modules/contest/commands/bindParticipantRole');
const manageParticipantRoleCommand = require('../modules/contest/commands/manageParticipantRole');
const setExternalSubmissionOptInCommand = require('../modules/contest/commands/setExternalSubmissionOptIn');
const viewSubmissionsCommand = require('../modules/contest/commands/viewSubmissions');
const viewSubmissionsContextCommand = require('../modules/contest/commands/viewSubmissionsContext');
const manageApplicationNotifyCommand = require('../modules/contest/commands/manageApplicationNotify');
const syncTournamentCommand = require('../modules/contest/commands/syncTournament');
const deleteTournamentCommand = require('../modules/contest/commands/deleteTournament');
const listBooklistsCommand = require('../modules/contest/commands/listBooklists');
const manageSyncExclusionCommand = require('../modules/contest/commands/manageSyncExclusion');
const keywordManagerCommand = require('../modules/autoCleanup/commands/keywordManager');
const exemptManagerCommand = require('../modules/autoCleanup/commands/exemptManager');
const cleanupManagerCommand = require('../modules/autoCleanup/commands/cleanupManager');
const summarizeChannelCommand = require('../modules/channelSummary/commands/summarizeChannel');
const summaryPresetCommand = require('../modules/channelSummary/commands/summaryPreset');
const createVoteCommand = require('../modules/voting/commands/createVote');
const notificationRolesCommand = require('../modules/voting/commands/notificationRoles');
const { messageCreateHandler } = require('./events/messageCreate');
const uploadCommand = require('../modules/selfFileUpload/commands/uploadFile');
const whoisCommand = require('../modules/selfFileUpload/commands/queryAnonymousLog');
const manageOptOutCommand = require('../modules/selfFileUpload/commands/manageOptOut.js');
const collectBackupsCommand = require('../modules/selfFileUpload/commands/collectBackups.js');
const setupRolePanelCommand = require('../modules/selfRole/commands/setupRolePanel');
const setupAdminPanelCommand = require('../modules/selfRole/commands/setupAdminPanel');
const recalculateActivityCommand = require('../modules/selfRole/commands/recalculateActivity');
const checkActivityCommand = require('../modules/selfRole/commands/checkActivity');
const debugRolesCommand = require('../modules/selfRole/commands/debugRoles');
const clearCooldownCommand = require('../modules/selfRole/commands/clearCooldown');
const configureRolesCommand = require('../modules/selfRole/commands/configureRoles');
const withdrawSelfRoleApplicationCommand = require('../modules/selfRole/commands/withdrawApplication');
const selfRoleOpsCommand = require('../modules/selfRole/commands/selfRoleOps');
const selfRoleWizardCommand = require('../modules/selfRole/commands/selfRoleWizard');
let selfRoleTestCommand = null;
if (String(process.env.SELF_ROLE_ENABLE_TEST_COMMANDS || '').toLowerCase() === 'true') {
    selfRoleTestCommand = require('../modules/selfRole/commands/selfRoleTest');
    console.log('[SelfRole] test commands enabled.');
}
const roleSyncConfigCommand = require('../modules/roleSync/commands/roleSyncConfig');
const { startPunishmentSystem } = require('../modules/punishment');
const punishCommand = require('../modules/punishment/commands/punish');
const disciplineCommand = require('../modules/punishment/commands/discipline');
const disciplineConfigCommand = require('../modules/punishment/commands/disciplineConfig');
const { startBotMessageSystem } = require('../modules/botMessage');
const botMessageCommand = require('../modules/botMessage/commands/botMessage');
const editBotMessageContextCommand = require('../modules/botMessage/commands/editBotMessageContext');
const { startControlledInviteSystem, controlledInviteGuildMemberAddHandler } = require('../modules/controlledInvite');
const controlledInviteConfigCommand = require('../modules/controlledInvite/commands/controlledInviteConfig');
const controlledInviteParamsCommand = require('../modules/controlledInvite/commands/controlledInviteParams');
const controlledInviteToggleCommand = require('../modules/controlledInvite/commands/controlledInviteToggle');
const viewMyControlledInviteStatusCommand = require('../modules/controlledInvite/commands/viewMyControlledInviteStatus');
const { startSafetySetupSystem } = require('../modules/safetySetup');
const mysteryCommand = require('../modules/mystery/commands/mysteryCommand');
const manageCommand = require('../modules/mystery/commands/manageCommand');
const mysteryGameStatsCommand = require('../modules/mystery/commands/gameStatsCommand');
const mysteryToggleCommand = require('../modules/mystery/commands/mysteryToggleCommand');
const { mysteryGuildMemberRemoveHandler } = require('../modules/mystery/events/guildMemberRemove');
const { mysteryGuildMemberUpdateHandler } = require('../modules/mystery/events/guildMemberUpdate');
const { handleGuildMemberUpdate: cowardPenaltyGuildMemberUpdateHandler, startCowardPenaltyRestorer } = require('../modules/mystery/services/cowardPenalty');
const DISCORD_REST_TIMEOUT_MS = (() => { const n = Number(process.env.DISCORD_REST_TIMEOUT_MS); return Number.isFinite(n) && n > 0 ? n : 15000; })();
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildMessageReactions, GatewayIntentBits.MessageContent], rest: { timeout: DISCORD_REST_TIMEOUT_MS } });
client.on('error', (err) => { console.error('\u274c [Discord] client error:', err); });
client.on('warn', (info) => { console.warn('\u26a0\ufe0f [Discord] client warn:', info); });
client.on('shardError', (err, shardId) => { console.error(`\u274c [Discord] shardError shard=${shardId}:`, err); });
client.on('shardDisconnect', (event, shardId) => { console.warn(`\u26a0\ufe0f [Discord] shardDisconnect shard=${shardId} code=${event?.code} reason=${event?.reason}`); });
client.on('shardReconnecting', (shardId) => { console.warn(`\u26a0\ufe0f [Discord] shardReconnecting shard=${shardId}`); });
client.on('shardResume', (shardId, replayedEvents) => { console.log(`\u2705 [Discord] shardResume shard=${shardId} replayed=${replayedEvents}`); });
try { client.rest.on('rateLimited', (info) => { const route = info?.route || info?.path || 'unknown'; const method = info?.method || 'unknown'; const timeToReset = info?.timeToReset; console.warn(`\u26a0\ufe0f [Discord][REST] rateLimited ${method} ${route} resetInMs=${timeToReset}`); }); } catch (_) {}
const HEALTH_LOG_INTERVAL_MINUTES = Number(process.env.HEALTH_LOG_INTERVAL_MINUTES || 0);
if (Number.isFinite(HEALTH_LOG_INTERVAL_MINUTES) && HEALTH_LOG_INTERVAL_MINUTES > 0) { setInterval(() => { console.log(`[Health] wsStatus=${client.ws?.status} ping=${client.ws?.ping} guilds=${client.guilds?.cache?.size} mem=${Math.round(process.memoryUsage().rss / 1024 / 1024)}MB`); }, Math.floor(HEALTH_LOG_INTERVAL_MINUTES * 60 * 1000)); }
client.commands = new Collection();
client.commands.set(pingCommand.data.name, pingCommand);
client.commands.set(setCheckChannelCommand.data.name, setCheckChannelCommand);
client.commands.set(setupFormCommand.data.name, setupFormCommand);
client.commands.set(deleteEntryCommand.data.name, deleteEntryCommand);
client.commands.set(withdrawProposalCommand.data.name, withdrawProposalCommand);
client.commands.set(setFormPermissionsCommand.data.name, setFormPermissionsCommand);
client.commands.set(setSupportPermissionsCommand.data.name, setSupportPermissionsCommand);
client.commands.set(reviewProposalCommand.data.name, reviewProposalCommand);
client.commands.set(setProposalReviewersCommand.data.name, setProposalReviewersCommand);
client.commands.set(creatorReviewCommand.data.name, creatorReviewCommand);
client.commands.set(setAllowCourtRoleCommand.data.name, setAllowCourtRoleCommand);
client.commands.set(applyToCourtCommand.data.name, applyToCourtCommand);
client.commands.set(deleteShitMessageCommand.data.name, deleteShitMessageCommand);
client.commands.set(muteShitUserCommand.data.name, muteShitUserCommand);
client.commands.set(seriousMuteCommand.data.name, seriousMuteCommand);
client.commands.set(selfModerationConfigCommand.data.name, selfModerationConfigCommand);
client.commands.set(checkMyCooldownCommand.data.name, checkMyCooldownCommand);
client.commands.set(getArchiveViewPermissionCommand.data.name, getArchiveViewPermissionCommand);
client.commands.set(setupContestApplicationCommand.data.name, setupContestApplicationCommand);
client.commands.set(manageTrackCommand.data.name, manageTrackCommand);
client.commands.set(setContestReviewersCommand.data.name, setContestReviewersCommand);
client.commands.set(reviewContestApplicationCommand.data.name, reviewContestApplicationCommand);
client.commands.set(updateContestInfoCommand.data.name, updateContestInfoCommand);
client.commands.set(updateContestTitleCommand.data.name, updateContestTitleCommand);
client.commands.set(initContestTagsCommand.data.name, initContestTagsCommand);
client.commands.set(manageAllowedForumsCommand.data.name, manageAllowedForumsCommand);
client.commands.set(manageExternalServersCommand.data.name, manageExternalServersCommand);
client.commands.set(cacheStats.data.name, cacheStats);
client.commands.set(regenerateContestMessagesCommand.data.name, regenerateContestMessagesCommand);
client.commands.set(bindParticipantRoleCommand.data.name, bindParticipantRoleCommand);
client.commands.set(manageParticipantRoleCommand.data.name, manageParticipantRoleCommand);
client.commands.set(setExternalSubmissionOptInCommand.data.name, setExternalSubmissionOptInCommand);
client.commands.set(viewSubmissionsCommand.data.name, viewSubmissionsCommand);
client.commands.set(viewSubmissionsContextCommand.data.name, viewSubmissionsContextCommand);
client.commands.set(manageApplicationNotifyCommand.data.name, manageApplicationNotifyCommand);
client.commands.set(syncTournamentCommand.data.name, syncTournamentCommand);
client.commands.set(deleteTournamentCommand.data.name, deleteTournamentCommand);
client.commands.set(listBooklistsCommand.data.name, listBooklistsCommand);
client.commands.set(manageSyncExclusionCommand.data.name, manageSyncExclusionCommand);
client.commands.set(keywordManagerCommand.data.name, keywordManagerCommand);
client.commands.set(exemptManagerCommand.data.name, exemptManagerCommand);
client.commands.set(cleanupManagerCommand.data.name, cleanupManagerCommand);
client.commands.set(summarizeChannelCommand.data.name, summarizeChannelCommand);
client.commands.set(summaryPresetCommand.data.name, summaryPresetCommand);
client.commands.set(createVoteCommand.data.name, createVoteCommand);
client.commands.set(notificationRolesCommand.data.name, notificationRolesCommand);
client.commands.set(uploadCommand.data.name, uploadCommand);
client.commands.set(whoisCommand.data.name, whoisCommand);
client.commands.set(manageOptOutCommand.data.name, manageOptOutCommand);
client.commands.set(collectBackupsCommand.data.name, collectBackupsCommand);
client.commands.set(setupRolePanelCommand.data.name, setupRolePanelCommand);
client.commands.set(setupAdminPanelCommand.data.name, setupAdminPanelCommand);
client.commands.set(recalculateActivityCommand.data.name, recalculateActivityCommand);
client.commands.set(checkActivityCommand.data.name, checkActivityCommand);
client.commands.set(debugRolesCommand.data.name, debugRolesCommand);
client.commands.set(clearCooldownCommand.data.name, clearCooldownCommand);
client.commands.set(configureRolesCommand.data.name, configureRolesCommand);
client.commands.set(withdrawSelfRoleApplicationCommand.data.name, withdrawSelfRoleApplicationCommand);
client.commands.set(selfRoleOpsCommand.data.name, selfRoleOpsCommand);
client.commands.set(selfRoleWizardCommand.data.name, selfRoleWizardCommand);
if (selfRoleTestCommand) { client.commands.set(selfRoleTestCommand.data.name, selfRoleTestCommand); }
client.commands.set(roleSyncConfigCommand.data.name, roleSyncConfigCommand);
client.commands.set(punishCommand.data.name, punishCommand);
client.commands.set(disciplineCommand.data.name, disciplineCommand);
client.commands.set(disciplineConfigCommand.data.name, disciplineConfigCommand);
client.commands.set(botMessageCommand.data.name, botMessageCommand);
client.commands.set(editBotMessageContextCommand.data.name, editBotMessageContextCommand);
client.commands.set(controlledInviteConfigCommand.data.name, controlledInviteConfigCommand);
client.commands.set(controlledInviteParamsCommand.data.name, controlledInviteParamsCommand);
client.commands.set(controlledInviteToggleCommand.data.name, controlledInviteToggleCommand);
client.commands.set(viewMyControlledInviteStatusCommand.data.name, viewMyControlledInviteStatusCommand);
client.commands.set(manageCommand.data.name, manageCommand);
client.commands.set(mysteryCommand.data.name, mysteryCommand);
client.commands.set(mysteryGameStatsCommand.data.name, mysteryGameStatsCommand);
client.commands.set(mysteryToggleCommand.data.name, mysteryToggleCommand);
if (String(process.env.MYSTERY_TEST_COMMANDS).toLowerCase() === 'true') { const pressureTestCommand = require('../modules/mystery/commands/pressureTestCommand'); client.commands.set(pressureTestCommand.data.name, pressureTestCommand); console.log('test mystery commands registered'); }
client.once(Events.ClientReady, async (readyClient) => {
    try { await clientReadyHandler(readyClient); } catch (err) { console.error('\u274c startup command sync failed:', err); try { readyClient.destroy(); } catch (_) {} process.exit(1); return; }
    printTimeConfig();
    startProposalChecker(readyClient); console.log('\u2705 proposal checker started');
    startCourtChecker(readyClient); console.log('\u2705 court checker started');
    startSelfModerationChecker(readyClient); console.log('\u2705 self-moderation checker started');
    startAttachmentCleanupScheduler(readyClient); console.log('\u2705 attachment cleanup scheduler started');
    startVoteChecker(readyClient); console.log('\u2705 vote checker started');
    console.log('\u2705 auto cleanup system started');
    startActivityTracker();
    await startCowardPenaltyRestorer(readyClient); console.log('\u2705 coward penalty restorer done');
    startSelfRoleApplicationChecker(readyClient);
    await syncMissedActivity(readyClient);
    startSelfRoleLifecycleScheduler(readyClient);
    startSelfRoleConsistencyChecker(readyClient);
    await startRoleSyncSystem(readyClient);
    await startPunishmentSystem(readyClient);
    await startBotMessageSystem(readyClient);
    await startControlledInviteSystem(readyClient);
    await startSafetySetupSystem(readyClient);
    console.log('\n\ud83e\udd16 Bot fully started, all systems operational!');
});
client.on(Events.InteractionCreate, interactionCreateHandler);
client.on(Events.MessageCreate, messageCreateHandler);
client.on(Events.GuildMemberAdd, roleSyncGuildMemberAddHandler);
client.on(Events.GuildMemberAdd, controlledInviteGuildMemberAddHandler);
client.on(Events.GuildMemberRemove, roleSyncGuildMemberRemoveHandler);
client.on(Events.GuildMemberUpdate, roleSyncGuildMemberUpdateHandler);
client.on(Events.GuildRoleDelete, roleSyncGuildRoleDeleteHandler);
client.on(Events.GuildMemberRemove, mysteryGuildMemberRemoveHandler);
client.on(Events.GuildMemberUpdate, mysteryGuildMemberUpdateHandler);
client.on(Events.GuildMemberUpdate, cowardPenaltyGuildMemberUpdateHandler);
function normalizeDiscordToken(raw) { if (!raw) return ''; let token = String(raw).trim(); if (!token) return ''; token = token.replace(/^Bot\s+/i, '').trim(); return token; }
const token = normalizeDiscordToken(process.env.DISCORD_TOKEN);
if (!token || token.includes('PASTE_YOUR_DISCORD_BOT_TOKEN')) { console.error('\u274c Missing DISCORD_TOKEN'); process.exit(1); }
if (token.split('.').length !== 3) { console.error('\u274c DISCORD_TOKEN format error'); process.exit(1); }
process.env.DISCORD_TOKEN = token;
client.login(token).catch((err) => { console.error('\u274c Discord login failed:', err); process.exit(1); });
